---
title: "Definite_code"
author: "Gemma Izquierdo"
date: "2026-08-30"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Functions to build the filters

First model:

```{r}
buildSignal <- function(para) {
  L <- matrix(0, p, p)
  L[upper.tri(L, TRUE)] <- para[1 : ((p*p+p)/2)]
  diag(L) <- exp(diag(L))
  
  modSignal <- dlm(
    FF = matrix(1, p, 1), 
    V = crossprod(L),
    GG = 1, 
    W = exp(para[(p*p+p)/2+1]), 
    m0 = 0, 
    C0 = 1e7
  )
  
  return(modSignal)
}

```

Second model:

p > 1:

```{r}
buildSignalnotfullphineq0 <- function(para) {
  
  VV <- matrix(0, p, p)
  VV[1, 1] <- exp(para[1])
  
  L <- matrix(0, p-1, p-1)
  L[upper.tri(L, TRUE)] <- para[2 : (1+((p-1)*(p-1)+(p-1))/2)]
  diag(L) <- exp(diag(L))
  LL <- crossprod(L) 
  
  VV[2:p, 2:p] <- LL

  ind <- (1+((p-1)*(p-1)+(p-1))/2)
  
  FF <- matrix(1, p, 1)
  FF[2:p,1] <- para[(ind+1):(ind+p-1)]
  
  ind <- (ind+p-1)
  
  modSignal <- dlm(
    FF = FF, 
    V = VV+matrix(1,p,p)*1e-6,
    GG = exp(para[ind+2]), 
    W = exp(para[ind+1]), 
    m0 = 0, 
    C0 = 1e4
  )
  
  return(modSignal)
}
```

p = 1:

```{r}
buildSignalnotfullphineq0_p1 <- function(para) {
  
  VV <- matrix(0, p, p)
  VV[1, 1] <- exp(para[1])
  
  FF <- 1
  
  modSignal <- dlm(
    FF = FF, 
    V = VV+1e-6,
    GG = para[2], 
    W = exp(para[3]), 
    m0 = 0, 
    C0 = 1e4
  )
  
  return(modSignal)
}
```
